server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # สำหรับการป้องกันการแคชไฟล์ที่อาจมีการเปลี่ยนแปลง
    location ~* \.(css|js|gif|jpe?g|png)$ {
        expires 1y;
        log_not_found off;
    }
}